trigger:
- master
- develop
- feature/*

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    version: '6.x'
  displayName: 'Install .NET 6'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Tests.csproj'
    arguments: '--configuration Release'


- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    arguments: '--configuration ${BuildConfiguration} --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
    publishWebProjects: False

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BotGeoGuesser'
    publishLocation: 'Container'